### ISSUE TITLE
Feature request: continent codes

### ISSUE THREAD

**Issue by mjball** [TakahikoKawasaki/nv-i18n#23]
It would be useful if one of the following were added:

- A (very small) enum for `ContinentCode` which lists all of the countries on that continent, or
- Each `CountryCode` enum had a `ContinentCode` field

If this is particularly burdensome I'm willing to put in the initial work to create the mapping – just let me know which implementation you prefer.

**Comment by TakahikoKawasaki** [comment]
Do you know specifications about continents which we can rely on? It seems *"[there are numerous ways of distinguishing the continents](http://en.wikipedia.org/wiki/Continent#Number_of_continents)"*.

Depending on the selected classification, some countries may belong to multiple continents. For example, if you wanted to distinguish Europe and Asia, you would see Russia in both continents. See also *"[Best way to store Country codes, names, and Continent in Java](http://stackoverflow.com/questions/713671/best-way-to-store-country-codes-names-and-continent-in-java)"*.

**Comment by mjball** [comment]
Unfortunately I do not. I took a crack at implementing this in my own codebase and ended up making some arbitrary decisions about what continent a country would be in. Some places are not even in a particular continent, like Ascension Island, Clipperton Island, Tristan de Cunha, etc. So perhaps this classification is better left to consumers of this library.
