### ISSUE TITLE
Aland Islands unicode character incorrect

### ISSUE THREAD

**Issue by aldenquimby** [TakahikoKawasaki/nv-i18n#24]
I just ran into an issue which I eventually tracked down to the unicode character used in `Aland Islands`:
```java
AX("\u212Bland Islands", "ALA", 248, Assignment.OFFICIALLY_ASSIGNED),
```
`CountryCode` uses [Angstrom Sign](http://www.fileformat.info/info/unicode/char/212b/index.htm), but according to [wiktionary](http://en.wiktionary.org/wiki/%C3%85), `\u00C5` appears to be the correct character (not `\u212B`), so I think [Latin Capital Letter A With Ring Above](http://www.fileformat.info/info/unicode/char/c5/index.htm) should be used instead.

**Comment by TakahikoKawasaki** [comment]
Thank you for your finding the bug. I fixed it and release nv-i18n version 1.15.
