### ISSUE TITLE
LanguageCode.ro.getName() return Rumansh instead of Romanian

### ISSUE THREAD

**Issue by simplysoft** [TakahikoKawasaki/nv-i18n#29]
In https://github.com/TakahikoKawasaki/nv-i18n/blob/master/src/main/java/com/neovisionaries/i18n/LanguageAlpha3Code.java#L4536
the name is wrong, it should be Romanian (as denoted in the wikipedia page linked above the definition)

**Comment by TakahikoKawasaki** [comment]
Thank you. I'll check it.

**Comment by TakahikoKawasaki** [comment]
Released a new version, `1.18`, which contains the fix. Thank you.
