### ISSUE TITLE
Add new currency code (BYN)

### ISSUE THREAD

**Issue by BuTeK** [TakahikoKawasaki/nv-i18n#31]
Please, add a new currency code to be used in Belarus with the July 1, 2016.

Amendment Number 161:
http://www.currency-iso.org/dam/isocy/downloads/dl_currency_iso_amendment_161.pdf

**Comment by TakahikoKawasaki** [comment]
@BuTeK Thank you for your information. I've released a new version, 1.19, including the new currency code, BYN.

**Comment by BuTeK** [comment]
Many thanks!
