### ISSUE TITLE
Add old currency RUR

### ISSUE THREAD

**Issue by BuTeK** [TakahikoKawasaki/nv-i18n#32]
Could you add the old currency of the Russian Federation RUR (code:810, minorUtit: 2).
Some of the services return 'RUR', which causes NPE in our code

**Comment by TakahikoKawasaki** [comment]
@BuTeK Released nv-i18n version 1.20 to include RUR.

**Comment by BuTeK** [comment]
You have helped us very much! Thank you!!!!

**Comment by TakahikoKawasaki** [comment]
You are welcome.
