### ISSUE TITLE
Chinese - Taiwan

### ISSUE THREAD

**Issue by GiovanniMorelli** [TakahikoKawasaki/nv-i18n#34]
Hi, there is no zh-TW (Chinese - Taiwan - CHT) code in the enum.

Below the link : 
https://msdn.microsoft.com/zh-tw/library/ee825488(v=cs.20).aspx

Thank for great work!!

**Comment by TakahikoKawasaki** [comment]
`LocaleCode` enum includes <code>[zh_TW](http://takahikokawasaki.github.io/nv-i18n/com/neovisionaries/i18n/LocaleCode.html#zh_TW)</code>. Isn't this what you want?
