### ISSUE TITLE
en_HK is omitted in LocaleCode

### ISSUE THREAD

**Issue by s1155030742** [TakahikoKawasaki/nv-i18n#36]
people in Hong Kong speak and read english :(

**Comment by TakahikoKawasaki** [comment]
Sorry for this late reply. I'll add it later.
(Sorry, I'm too busy as a founder of [Authlete, Inc.](https://www.authlete.com/))

**Comment by TakahikoKawasaki** [comment]
Released nv-i18n version 1.22 which includes [en_HK](http://takahikokawasaki.github.io/nv-i18n/com/neovisionaries/i18n/LocaleCode.html#en_HK).
