### ISSUE TITLE
No Kazakh locale codes

### ISSUE THREAD

**Issue by flodiebold** [TakahikoKawasaki/nv-i18n#37]
There are no entries in LocaleCode for kazakhstan at all. Would you mind adding kk_KZ and ru_KZ?

**Comment by TakahikoKawasaki** [comment]
Sorry for this late reply. I'll add them later.
(Sorry, I'm too busy as a founder of [Authlete, Inc.](https://www.authlete.com/))

**Comment by TakahikoKawasaki** [comment]
Released nv-i18n version 1.22 which includes <code>[kk_KZ](http://takahikokawasaki.github.io/nv-i18n/com/neovisionaries/i18n/LocaleCode.html#kk_KZ)</code> and <code>[ru_KZ](http://takahikokawasaki.github.io/nv-i18n/com/neovisionaries/i18n/LocaleCode.html#ru_KZ)</code>.

**Comment by flodiebold** [comment]
Great, thanks a lot!
