### ISSUE TITLE
Correct obsolete currency codes

### ISSUE THREAD

**Issue by fink-stanislav** [TakahikoKawasaki/nv-i18n#38]
Correct obsolete currency codes

1. Currency code for Belarusian ruble (BYR) is now obsolete. New one (BYN) should be used instead.
2. Currency code for Lithuanian lit (LTL) is now obsolete. A code for Euro should be used instead. 
3. Lithuania's country code should be added to array of countries which use Euro.

**Comment by fink-stanislav** [comment]
I will provide a pull request for fixing this soon

**Comment by beresfordt** [comment]
👍

**Comment by TakahikoKawasaki** [comment]
@fink-stanislav Sorry for this late response and thank you for your suggestion. I released nv-i18n-1.24 which includes your suggestions. I was thinking of merging #39 but gave it up. Instead, I manually imported your suggestion.
