### ISSUE TITLE
Send Binery Proirity

### ISSUE THREAD

**Issue by saeedmozaffari** [TakahikoKawasaki/nv-i18n#42]
is there any for set priority in `sendBinery()`?

for example i have a byte array with `10 Mb` size, and i used from  `sendBinery()`.  Before this byte array is really sent and `onFrameSent()` called , i want to send another byte array with just  `1 byte` , how can i send second array with lower size before send first byte array, and do not wait to send a bigger byte array?

**Comment by mjball** [comment]
Would you mind linking to the code you're referring to? I suspect you have the wrong repo.

**Comment by saeedmozaffari** [comment]
I'm trying to ask my question better. 
I have a messenger .
my user uploading a chunk of file with size **1 Mb** (for example : complete file size is **5 Mb**) ; then before this chunk is sent to the server ( `onFrameSent()` ), sends a simple text message with **10 byte** size.
now we should waiting for send file chunk and after than can send simple text.

is there any way that for this conditions we send simple text in **parallel** state with file chunk and don't wait for upload file, just in **one connection**?

**Comment by Vampire** [comment]
As you found out that here is the wrong place (https://github.com/TakahikoKawasaki/nv-websocket-client/issues/131), please close this issue.
