### ISSUE TITLE
Add currency codes for MRU and STN

### ISSUE THREAD

**Issue by ctgnz** [TakahikoKawasaki/nv-i18n#48]
Two new currency codes have been added to ISO-4217 at the start of 2018. Please add support for these currencies ASAP.

- MRU 929, Mauritanian Ouguiya (replaces MRO) https://www.currency-iso.org/dam/isocy/downloads/dl_currency_iso_amendment_165.pdf 

- STN 930, Sao Tome and Principe Dobra (replaces STD) https://www.currency-iso.org/dam/isocy/downloads/dl_currency_iso_amendment_164.pdf

**Comment by TakahikoKawasaki** [comment]
I'm sorry for this late reply, and I thank you for the information about new currency codes.

`MRU` and `STN` were added, and `MRO` and `STD` were marked as deprecated. nv-i18n 1.23 which includes the changes was released.
