### ISSUE TITLE
Make methods public

### ISSUE THREAD

**Issue by DanieleTorino** [TakahikoKawasaki/nv-i18n#49]
Could you please make methods such as `getByAlpha2Code`,  `getByAlpha3Code` etc. public?

e.g. If a value needs to be a valid ISO 3166-1 alpha-2 but not alpha-3 this would make it easier to check.
Currently, the value needs to be checked if the length has the appropriate length prior to calling `getByCode`.

Thanks

**Comment by TakahikoKawasaki** [comment]
I made three `getByAlpha?Code(String)` methods public and released nv-i18n 1.23.

**Comment by DanieleTorino** [comment]
Oh wow. That was quick. Thank you.
