### ISSUE TITLE
How about letting CountryCode implement an interface.

### ISSUE THREAD

**Issue by mihxil** [TakahikoKawasaki/nv-i18n#53]
I would like that CountryCode implements some 'Region' interface. This would make it possible to make more implementations, like e.g. 'former countries' (I'm setting up something at https://github.com/mihxil/i18n-formerly-assigned).

I suggest something like this:
https://github.com/mihxil/nv-i18n/blob/master/src/main/java/com/neovisionaries/i18n/Region.java

How would you feel about something like this?

**Comment by derekmahar** [comment]
I had a similar idea when I created [CustomCountryCode](https://github.com/derekmahar/nv-i18n/blob/userAssigned2/src/main/java/com/neovisionaries/i18n/CustomCountryCode.java) as an interface for [CountryCode](https://github.com/TakahikoKawasaki/nv-i18n/blob/master/src/main/java/com/neovisionaries/i18n/CountryCode.java) in order to implement class [StandardOrUserAssignedCountryCode](https://github.com/derekmahar/nv-i18n/blob/userAssigned2/src/main/java/com/neovisionaries/i18n/StandardOrUserAssignedCountryCode.java) to accommodate [user-assigned country codes](https://github.com/TakahikoKawasaki/nv-i18n/issues/25).

**Comment by GuiSim** [comment]
I'd use this right now for an API that returns `XX`, which can be used to denote an unknown country (why they didn't use null, I do not know).

**Comment by mihxil** [comment]
I was rather hoping that @TakahikoKawasaki would react how he'd see something like this. I can make a pull request, but may be it's better to know beforehand what kind of reaction to expect.

**Comment by mihxil** [comment]
Actually I was thinking, there is a possible other approach, and I made a new project which provides this 'Region' interface along with a few implementations (one of them or course based on nv-i18n).

So, in this way we actually can add the Region interface without having to add it here.  I made it pluggable via java service provider interfaces. So you could simply made a 'RegionProvider' and make it return whatever extra Regions you'd like.

I hacked this up in a few spare hours, so it's not yet quite finished:
https://github.com/mihxil/i18n-regions

**Comment by derekmahar** [comment]
I think this approach makes sense. As an enumeration, the existing [CountryCode](https://github.com/TakahikoKawasaki/nv-i18n/blob/master/src/main/java/com/neovisionaries/i18n/CountryCode.java) implementation does not allow clients to add new country codes.  It is essentially closed to extension.  By introducing interface [Region](https://github.com/mihxil/i18n-regions/blob/master/src/main/java/org/meeuw/i18n/Region.java), you open `CountryCode` to extension through custom implementations.

**Comment by derekmahar** [comment]
What is the purpose of `RegionProvider`?

**Comment by mihxil** [comment]
I takes the roles of static methods, like `.values()` and `getByCode`.   Using java's  `java.util.ServiceLoader' to access all registered implementations.

**Comment by derekmahar** [comment]
I noticed that   https://github.com/mihxil/i18n-regions assumes Java 8, but nv-i18n does not.  This would introduce a compatibility issue for clients still using Java 7 and earlier.

**Comment by mihxil** [comment]
Yes, but really? Java 7 was end of life a few years ago, wasn't it? I actually considered making it java 11!

But well, if somebody really considers this an obstacle I'd gladly consider making it java 7 compatible. I suppose that would be relatively simple.

**Comment by mihxil** [comment]
I in the end didn't make it java 7 compatible. The code depended on Stream-api's and I think it would be silly to make everything different just to still be able to support java 7.

It will be java 8+. I tried to even support java 9 module-info.java as good as possible.
