### ISSUE TITLE
add a boolean switch for lower case findByName

### ISSUE THREAD

**Issue by vahidhedayati** [TakahikoKawasaki/nv-i18n#65]
Two new methods perhaps :

```

public static List<CountryCode> findByName(String regex, boolean lc) {
..


public static List<CountryCode> findByName(Pattern pattern, boolean lc)
...

```

Then 
https://github.com/TakahikoKawasaki/nv-i18n/blob/master/src/main/java/com/neovisionaries/i18n/CountryCode.java#L2960 
from 
```
if (pattern.matcher(entry.getName()).matches())
```
To something like:
```
if (lc && pattern.matcher(entry.getName().toLowerCase()).matches()||!lc  && pattern.matcher(entry.getName()).matches() )

```

**Comment by TakahikoKawasaki** [comment]
@vahidhedayati Use <code>[Pattern.CASE_INSENSITIVE](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html#CASE_INSENSITIVE)</code> or `(?i)` when you create a `Pattern` instance.

**Comment by vahidhedayati** [comment]
I think to use `Pattern.CASE_INSENSITIVE` the `findByName` still needs another method to accept the pattern type. I checked through `CountryCode` and `Pattern.compile(regex)` is what has been declared everywhere.

[According to the docs:](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html):

```
public static Pattern compile(String regex,
              int flags)
Compiles the given regular expression into a pattern with the given flags.
Parameters:
regex - The expression to be compiled
flags - Match flags, a bit mask that may include CASE_INSENSITIVE 
```

I will try with `?i` thanks
